#https://chatgpt.com/c/68da2405-2b00-8328-8336-c8ba66181d61
#Containers (transfer configurations to other machine)
#docker file instucts to install dependencies
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
    volumes: #location of the container
    network: #if multiple machine

  #pasunod og run
  phpymyadmin:
    image: phpmyadmin:5.2
  environment:
    depends_on:
    ports:
    volumes:
    network:
